name: django-app

on:
  push:
    branch: [ main ]
  pull_request:
    branch: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E501,W503,W504 app setup
      - name: Coverage report
        env:
          SECRET_KEY: "django-insecure-kigx$f(5*b0sg41&y8e%#@wlquv0#ggtt6nb053l$f!(ll4ll4"
        run: |
          pip install coverage
          coverage run manage.py test
          coverage retort